### ISSUE TITLE
entryPointMethodName Parameter is not found 

### ISSUE THREAD

**Issue by mohShahbal** [diegohzea/overlay_pop_up#4]
there is no entryPointMethodName parameter, while package documentation has this parameter.

PARAMS

height is not required by default is MATCH_PARENT

width is not required by default is MATCH_PARENT

verticalAlignment is not required by default is CENTER for more info see: https://developer.android.com/reference/android/view/Gravity

horizontalAlignment is not required by default is CENTER for more info see: https://developer.android.com/reference/android/view/Gravity

backgroundBehavior by default is focusable flag that is you can take focus inside a overlay for example inside a textfield and [tapThrough] you can tap through the overlay background even if has MATCH_PARENT sizes.

screenOrientation by default orientation is portrait.

closeWhenTapBackButton by default when user presses back button the overlay no has any action if you pass true then back button will close overlay.

isDraggable by default is false therefore the overlay can´t be dragged.

**entryPointMethodName by default is 'overlayPopUp' if you want you can change it**

**Comment by diegohzea** [comment]
The parameter entryPointMethodName was added, you will find it in version 1.0.5.
